version: '3.8'                                                                                               docker-compose.yml                                                                                                             version: '3.8'

services:
  prometheus-service-demo-0:
    image: docker.io/julius/prometheus-demo-service:latest
    ports:
      - "10000:8080"
    container_name: prometheus-service-demo-0

  prometheus-service-demo-1:
    image: docker.io/julius/prometheus-demo-service:latest
    ports:
      - "20000:8080"
    container_name: prometheus-service-demo-1

  prometheus-service-demo-2:
    image: docker.io/julius/prometheus-demo-service:latest
    ports:
      - "30000:8080"
    container_name: prometheus-service-demo-2

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
    container_name: grafana

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    container_name: node-exporter

volumes:
  grafana-storage:
