{
 "title": "Métricas Latencia",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Promedio - Latencia HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(demo_api_request_duration_seconds_sum[5m])) by (method, path) \r\n/ \r\nsum(rate(demo_api_request_duration_seconds_count[5m])) by (method, path)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 - Latencia HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(demo_api_request_duration_seconds_bucket[5m])) by (le, method, path))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P90 - Latencia HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(demo_api_request_duration_seconds_bucket[5m])) by (le, method, path, status))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}